[project]
name = "mary2ish"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fast-agent-mcp>=0.2.58",
    "streamlit>=1.52.2",
    "pydantic>=2.12.5",
    "pytest>=9.0.2",
]

[dependency-groups]
dev = [
    "pytest-asyncio>=1.3.0",
]
